# Generated by Django 5.1.8 on 2025-06-16 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку.",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку.",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Опишите действие, которое будет выполнять привычка.",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        default=False,
                        help_text="Признак, является ли привычка приятной.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки в днях.",
                        verbose_name="Переодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение за выполнение привычки.",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        help_text="Время на выполнение привычки в секундах.",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Признак публичности привычки.",
                        verbose_name="Публичность",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата создания привычки",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "last_notification_sent",
                    models.DateField(
                        blank=True,
                        help_text="Когда в последний раз отправлялось уведомление",
                        null=True,
                        verbose_name="Дата последнего уведомления",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата выполнения привычки.",
                        verbose_name="Дата выполнения",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Статус выполнения привычки: выполнена или нет.",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Заметки о выполнении привычки.",
                        null=True,
                        verbose_name="Заметки",
                    ),
                ),
            ],
        ),
    ]
